#ddev-generated

http:
  routers:
    
    
    craftstart-web-80-http:
      
      rule: HostRegexp(`craftstart.ddev.site`, `starter.ddev.site`)
      
      middlewares:
        - autodetect
      service: "craftstart-web-80-http"
      tls: false
      entrypoints:
        - http-80
    
    
    craftstart-web-8025-http:
      
      rule: HostRegexp(`craftstart.ddev.site`, `starter.ddev.site`)
      
      middlewares:
        - autodetect
      service: "craftstart-web-8025-http"
      tls: false
      entrypoints:
        - http-8025
    
    
    craftstart-web-3000-http:
      
      rule: HostRegexp(`craftstart.ddev.site`, `starter.ddev.site`)
      
      middlewares:
        - autodetect
      service: "craftstart-web-3000-http"
      tls: false
      entrypoints:
        - http-3001
    
    
    
    
    
    
    
    
    craftstart-web-80-https:
      
      rule: HostRegexp(`craftstart.ddev.site`, `starter.ddev.site`)
      
      middlewares:
        - autodetect
      service: "craftstart-web-80-https"
      
      tls: true
      
      entrypoints:
        - http-443
    
    
    craftstart-web-8025-https:
      
      rule: HostRegexp(`craftstart.ddev.site`, `starter.ddev.site`)
      
      middlewares:
        - autodetect
      service: "craftstart-web-8025-https"
      
      tls: true
      
      entrypoints:
        - http-8026
    
    
    craftstart-web-3000-https:
      
      rule: HostRegexp(`craftstart.ddev.site`, `starter.ddev.site`)
      
      middlewares:
        - autodetect
      service: "craftstart-web-3000-https"
      
      tls: true
      
      entrypoints:
        - http-3000
    
    

  # autodetect won't be needed in Traefik 3 https://github.com/traefik/traefik/pull/9546
  middlewares:
    autodetect:
      contentType:
        autoDetect: false

  services:
    
    craftstart-web-80-http:
      loadbalancer:
        servers:
          - url: http://ddev-craftstart-web:80
    
    craftstart-web-8025-http:
      loadbalancer:
        servers:
          - url: http://ddev-craftstart-web:8025
    
    craftstart-web-3000-http:
      loadbalancer:
        servers:
          - url: http://ddev-craftstart-web:3000
    
    craftstart-web-80-https:
    
      loadbalancer:
        servers:
          - url: http://ddev-craftstart-web:80
    
    craftstart-web-8025-https:
    
      loadbalancer:
        servers:
          - url: http://ddev-craftstart-web:8025
    
    craftstart-web-3000-https:
    
      loadbalancer:
        servers:
          - url: http://ddev-craftstart-web:3000
    


tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/craftstart.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/craftstart.key

